targets:
  $default:
    sources:
      include:
        - $package$
        - lib/**
        - test/**
        - example/lib/**
        - example/test/**
      exclude:
        - example/**/.dart_tool/**
        - example/**/flutter/ephemeral/**
        - example/**/.plugin_symlinks/**
        - example/**/build/**
    builders:
      flux_method_generator:service_generator:
        enabled: true


