name: squadron_first_example
description: Squadron-first service framework example with transparent method calls
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_service_framework:
    path: ../../
  squadron: ^6.2.0

dev_dependencies:
  test: ^1.26.3
  build_runner: ^2.7.0