name: flux_method_generator
description: Code generator for dart_service_framework service contracts (clients/dispatchers)
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.4.0
  build: ^2.4.0
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.0

publish_to: none

